/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adaptavist;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ClassWithConflictingPropTest {
    @Test void someLibraryMethodReturnsTrue() {
        ClassWithConflictingProp classUnderTest = new ClassWithConflictingProp();
        assertTrue(classUnderTest.isConflictingProperty(), "isConflictingProperty should return 'true'");

        assertEquals(classUnderTest.getConflictingProperty(), "getter");
    }
}
