/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adaptavist;

public class ClassWithConflictingProp {
    public boolean isConflictingProperty() {
        return true;
    }

    public String getConflictingProperty() {
        return "getter";
    }
}
